// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_simulate_games
DataFrame cpp_simulate_games(int n, IntegerVector strategies, int hand_size, bool stacking, int seed);
RcppExport SEXP _uno_cpp_simulate_games(SEXP nSEXP, SEXP strategiesSEXP, SEXP hand_sizeSEXP, SEXP stackingSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type strategies(strategiesSEXP);
    Rcpp::traits::input_parameter< int >::type hand_size(hand_sizeSEXP);
    Rcpp::traits::input_parameter< bool >::type stacking(stackingSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_simulate_games(n, strategies, hand_size, stacking, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_uno_cpp_simulate_games", (DL_FUNC) &_uno_cpp_simulate_games, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_uno(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
