# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Simulate Uno games (Rcpp).
#'
#' @param n number of games
#' @param strategies integer vector, one per player (0=random, 1=aggressive,
#'   2=colour_matcher)
#' @param hand_size starting hand size
#' @param stacking allow +2/+4 stacking on like-typed cards
#' @param seed RNG seed
#' @return a DataFrame with columns game, winner_idx, winner_strategy,
#'   n_turns, cards_left
#' @export
cpp_simulate_games <- function(n, strategies, hand_size = 7L, stacking = FALSE, seed = 1L) {
    .Call('_uno_cpp_simulate_games', PACKAGE = 'uno', n, strategies, hand_size, stacking, seed)
}

